# Generated by Django 4.1 on 2024-06-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('restaurant', '0003_order_tablesrestaurant_productsorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.waiter')),
            ],
        ),
    ]
